### PR TITLE
Back merge main to teams_interop

### PR DESCRIPTION
**Pull request by jimchou-dev**
## Purpose
* Back merge main to teams_interop branch
* Using calling SDK 1.1.0-beta.1

## Does this introduce a breaking change?
```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ x ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What to Check
Verify that the following are valid
* Test if participant list updates dynamically
* Test if spotlight screen sharing
* Test if user can switch camera front/back (in lobby and in meeting)

### CODE REVIEW

**Review by cheukchuen — COMMENTED** [review]
Just merged the config screen camera switching feature into `main`. Might want to include that in this back merge.

**Comment by jimchou-dev** [comment]
> Just merged the config screen camera switching feature into `main`. Might want to include that in this back merge.

Added config screen camera switching to be included in the backmerge

**Review by Gemakk — CHANGES_REQUESTED** [review]
When you're denied entry to a Teams meeting when you had video on, it will not be on when you return to the Lobby

**Comment by jimchou-dev** [comment]
> When you're denied entry to a Teams meeting when you had video on, it will not be on when you return to the Lobby

Good catch @Gemakk looks like this bug exist in teams_interop branch before this commit. I've created a bug for it:
https://skype.visualstudio.com/SPOOL/_workitems/edit/2478186

**Review by AmyL219 — APPROVED** [review]

**Review by Gemakk — APPROVED** [review]
Tested

**Pull request merged**
