### PR TITLE
[Refactor] Update images to svg

### PR DESCRIPTION
**Pull request by vhuseinova-msft**
## Purpose

* Update all images with svg files

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
1) Open the application
2) Navigate to different screens
```

## What to Check
Verify that the following are valid
* UI elements are shown as expected on iPhones and iPads

### CODE REVIEW

**Review by palatter — APPROVED** [review]
Looks good!

**Comment by palatter** [comment]
Just to confirm, only images without fixed height/width use preserve vector data now?

**Comment by vhuseinova-msft** [comment]
@palatter no, "Preserve Vector Data" option is turned off for all assets right not (other that app icon as it's still png files). The option was turned off for most of pdf images earlier and only for icons on bottom/side view it was set to true. I've checked UI after updates on some of iPhones and iPads and UI looks the same as it was before  #the changes.

**Comment by vhuseinova-msft** [comment]
"Preserve Vector Data" option is turned on for all images for providing better UX and as it doesn't change the size of the ipa much.

**Review by palatter — APPROVED** [review]
Looks good and tested.

**Review by AmyL219 — APPROVED** [review]
Briefly tested.

**Pull request merged**
